In [1]:
import numpy as np
from scipy.spatial.distance import euclidean
from scipy.spatial.distance import cosine

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [3]:
euclidean(a, b)

4.4721359549995796

In [6]:
from UBCFBase import UBCFBase

In [8]:
import pandas as pd

In [9]:
raw_rating_df = pd.read_csv('new_ratings_all.txt',
                                    sep=':',
                                    header=None,
                                    names=['uid', 'iid', 'rating', 'date', 'comment_type'],
                                    dtype={'uid': np.str, 'iid': np.str})

In [10]:
uci = UBCFBase.compute_UCI(raw_rating_df)

In [11]:
uci

uid
101030945          0.029148
101306532          0.154652
102009494          0.018775
102027189          0.303559
10241572           0.265665
103402492          0.121332
1049890            0.053085
104991310          0.692577
10564710           0.194293
106531709          0.017599
1069770            0.174749
1079180            0.176569
108016742          0.188523
109954597          0.525197
1111383            0.073820
114225619          0.003322
114300394          0.121772
1145037            0.149523
114515320          0.711838
114520027          0.055460
115608638          0.091148
116739424          0.700177
119030590          0.019035
119591426          0.027831
120076971          0.140121
120845613          0.234471
121362410          0.701131
121806653          0.279745
122948297          0.159476
1230022            0.069708
                     ...   
xyiyi              0.126077
yange1991          0.172502
yatouzhu           0.439190
yfqc24pippo        0.493379
yiba            

In [12]:
urdi = UBCFBase.compute_URDI(raw_rating_df)

In [13]:
urdi

uid
101030945          3.974599
101306532          0.608790
102009494          2.585939
102027189          0.000000
10241572           1.964564
103402492          1.905299
1049890            1.672248
104991310          0.484569
10564710           0.515079
106531709          2.466292
1069770            8.898924
1079180            0.510166
108016742          1.747075
109954597          0.879121
1111383            1.317744
114225619          1.445713
114300394          1.616780
1145037            1.413606
114515320          0.448203
114520027          1.903057
115608638          2.200538
116739424          0.000000
119030590          1.714527
119591426          1.013868
120076971          3.846588
120845613          2.036048
121362410          0.850092
121806653          2.831688
122948297          1.377639
1230022            0.744759
                     ...   
xyiyi              1.587895
yange1991          0.950370
yatouzhu           1.924215
yfqc24pippo        2.920776
yiba            

In [14]:
behavior_matrix = pd.concat([uci, urdi], axis=1)

In [15]:
behavior_matrix

0         1
uid                                
101030945        0.029148  3.974599
101306532        0.154652  0.608790
102009494        0.018775  2.585939
102027189        0.303559  0.000000
10241572         0.265665  1.964564
103402492        0.121332  1.905299
1049890          0.053085  1.672248
104991310        0.692577  0.484569
10564710         0.194293  0.515079
106531709        0.017599  2.466292
1069770          0.174749  8.898924
1079180          0.176569  0.510166
108016742        0.188523  1.747075
109954597        0.525197  0.879121
1111383          0.073820  1.317744
114225619        0.003322  1.445713
114300394        0.121772  1.616780
1145037          0.149523  1.413606
114515320        0.711838  0.448203
114520027        0.055460  1.903057
115608638        0.091148  2.200538
116739424        0.700177  0.000000
119030590        0.019035  1.714527
119591426        0.027831  1.013868
120076971        0.140121  3.846588
120845613        0.234471  2.036048
121362410        0.701131  0.850092
121806653        0.279745  2.831688
122948297        0.159476  1.377639
1230022          0.069708  0.744759
...                   ...       ...
xyiyi            0.126077  1.587895
yange1991        0.172502  0.950370
yatouzhu         0.439190  1.924215
yfqc24pippo      0.493379  2.920776
yiba             0.282241  1.024627
yicai7094        0.109643  1.310764
yinxiang         0.665925  1.225598
yizhibanjie      0.116943  3.350370
yolanta1030      0.417633  2.837445
ytrr             0.147511  2.928642
yuhanxi          0.197379  3.196016
yungweitung      0.153969  4.654077
yuuffy           0.304602  1.643040
z123456789321    0.007742  3.124715
z14759230        0.175950  0.862549
zengdi77         0.568606  0.653289
zeus93           0.106608  3.756116
zhangxiaoduo123  0.391457  0.709429
zhangyiwang      0.243508  1.720291
zhouruopei       0.524767  1.363105
zhuangdikun      0.372682  2.784053
zhushejia        0.395568  2.259548
zi1230           0.048547  2.101501
zihaozai0407     0.578905  0.603406
zmzy             0.354463  0.313900
zoe-77           0.033320  2.026757
zombieleslie     0.272161  2.023162
zurich0o0        0.425408  1.753336
zwj514235        0.212405  2.164580
zyjj141          0.521430  4.040796

[971 rows x 2 columns]

In [18]:
behavior_matrix.ix['101030945'].values

array([ 0.02914812,  3.97459884])

In [19]:
np.random.seed(0)
df = pd.DataFrame(np.random.binomial(1, 0.5, size = (100, 5)))
print(df.head())

   0  1  2  3  4
0  1  1  1  1  0
1  1  0  1  1  0
2  1  1  1  1  0
3  0  0  1  1  1
4  1  1  0  1  0


In [20]:
from sklearn.metrics.pairwise import pairwise_distances

In [21]:
cosine(a, b)

0.33333333333333337

In [22]:
test = np.array([a, b])

In [23]:
test

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [25]:
pairwise_distances(test)

array([[ 0.        ,  4.47213595],
       [ 4.47213595,  0.        ]])

In [28]:
pd.DataFrame.corr(behavior_matrix.T)

uid              101030945  101306532  102009494  102027189  10241572  \
uid                                                                     
101030945              1.0        1.0        1.0       -1.0       1.0   
101306532              1.0        1.0        1.0       -1.0       1.0   
102009494              1.0        1.0        1.0       -1.0       1.0   
102027189             -1.0       -1.0       -1.0        1.0      -1.0   
10241572               1.0        1.0        1.0       -1.0       1.0   
103402492              1.0        1.0        1.0       -1.0       1.0   
1049890                1.0        1.0        1.0       -1.0       1.0   
104991310             -1.0       -1.0       -1.0        1.0      -1.0   
10564710               1.0        1.0        1.0       -1.0       1.0   
106531709              1.0        1.0        1.0       -1.0       1.0   
1069770                1.0        1.0        1.0       -1.0       1.0   
1079180                1.0        1.0        1.0       -1.0       1.0   
108016742              1.0        1.0        1.0       -1.0       1.0   
109954597              1.0        1.0        1.0       -1.0       1.0   
1111383                1.0        1.0        1.0       -1.0       1.0   
114225619              1.0        1.0        1.0       -1.0       1.0   
114300394              1.0        1.0        1.0       -1.0       1.0   
1145037                1.0        1.0        1.0       -1.0       1.0   
114515320             -1.0       -1.0       -1.0        1.0      -1.0   
114520027              1.0        1.0        1.0       -1.0       1.0   
115608638              1.0        1.0        1.0       -1.0       1.0   
116739424             -1.0       -1.0       -1.0        1.0      -1.0   
119030590              1.0        1.0        1.0       -1.0       1.0   
119591426              1.0        1.0        1.0       -1.0       1.0   
120076971              1.0        1.0        1.0       -1.0       1.0   
120845613              1.0        1.0        1.0       -1.0       1.0   
121362410              1.0        1.0        1.0       -1.0       1.0   
121806653              1.0        1.0        1.0       -1.0       1.0   
122948297              1.0        1.0        1.0       -1.0       1.0   
1230022                1.0        1.0        1.0       -1.0       1.0   
...                    ...        ...        ...        ...       ...   
xyiyi                  1.0        1.0        1.0       -1.0       1.0   
yange1991              1.0        1.0        1.0       -1.0       1.0   
yatouzhu               1.0        1.0        1.0       -1.0       1.0   
yfqc24pippo            1.0        1.0        1.0       -1.0       1.0   
yiba                   1.0        1.0        1.0       -1.0       1.0   
yicai7094              1.0        1.0        1.0       -1.0       1.0   
yinxiang               1.0        1.0        1.0       -1.0       1.0   
yizhibanjie            1.0        1.0        1.0       -1.0       1.0   
yolanta1030            1.0        1.0        1.0       -1.0       1.0   
ytrr                   1.0        1.0        1.0       -1.0       1.0   
yuhanxi                1.0        1.0        1.0       -1.0       1.0   
yungweitung            1.0        1.0        1.0       -1.0       1.0   
yuuffy                 1.0        1.0        1.0       -1.0       1.0   
z123456789321          1.0        1.0        1.0       -1.0       1.0   
z14759230              1.0        1.0        1.0       -1.0       1.0   
zengdi77               1.0        1.0        1.0       -1.0       1.0   
zeus93                 1.0        1.0        1.0       -1.0       1.0   
zhangxiaoduo123        1.0        1.0        1.0       -1.0       1.0   
zhangyiwang            1.0        1.0        1.0       -1.0       1.0   
zhouruopei             1.0        1.0        1.0       -1.0       1.0   
zhuangdikun            1.0        1.0        1.0       -1.0       1.0   
zhushejia              1.0        1.0        1.0       -1.

In [29]:
behavior_matrix

0         1
uid                                
101030945        0.029148  3.974599
101306532        0.154652  0.608790
102009494        0.018775  2.585939
102027189        0.303559  0.000000
10241572         0.265665  1.964564
103402492        0.121332  1.905299
1049890          0.053085  1.672248
104991310        0.692577  0.484569
10564710         0.194293  0.515079
106531709        0.017599  2.466292
1069770          0.174749  8.898924
1079180          0.176569  0.510166
108016742        0.188523  1.747075
109954597        0.525197  0.879121
1111383          0.073820  1.317744
114225619        0.003322  1.445713
114300394        0.121772  1.616780
1145037          0.149523  1.413606
114515320        0.711838  0.448203
114520027        0.055460  1.903057
115608638        0.091148  2.200538
116739424        0.700177  0.000000
119030590        0.019035  1.714527
119591426        0.027831  1.013868
120076971        0.140121  3.846588
120845613        0.234471  2.036048
121362410        0.701131  0.850092
121806653        0.279745  2.831688
122948297        0.159476  1.377639
1230022          0.069708  0.744759
...                   ...       ...
xyiyi            0.126077  1.587895
yange1991        0.172502  0.950370
yatouzhu         0.439190  1.924215
yfqc24pippo      0.493379  2.920776
yiba             0.282241  1.024627
yicai7094        0.109643  1.310764
yinxiang         0.665925  1.225598
yizhibanjie      0.116943  3.350370
yolanta1030      0.417633  2.837445
ytrr             0.147511  2.928642
yuhanxi          0.197379  3.196016
yungweitung      0.153969  4.654077
yuuffy           0.304602  1.643040
z123456789321    0.007742  3.124715
z14759230        0.175950  0.862549
zengdi77         0.568606  0.653289
zeus93           0.106608  3.756116
zhangxiaoduo123  0.391457  0.709429
zhangyiwang      0.243508  1.720291
zhouruopei       0.524767  1.363105
zhuangdikun      0.372682  2.784053
zhushejia        0.395568  2.259548
zi1230           0.048547  2.101501
zihaozai0407     0.578905  0.603406
zmzy             0.354463  0.313900
zoe-77           0.033320  2.026757
zombieleslie     0.272161  2.023162
zurich0o0        0.425408  1.753336
zwj514235        0.212405  2.164580
zyjj141          0.521430  4.040796

[971 rows x 2 columns]

In [36]:
usr_a = behavior_matrix.ix['101030945']

In [37]:
usr_b = behavior_matrix.ix['101306532']

In [41]:
distance_to_mean_a = usr_a - usr_a.mean()

In [42]:
distance_to_mean_b = usr_b - usr_b.mean()

In [46]:
fenzi = np.sum(distance_to_mean_a * distance_to_mean_b)

In [47]:
fenmu_a = np.sqrt(np.sum(distance_to_mean_a * distance_to_mean_a))

In [48]:
fenmu_b = np.sqrt(np.sum(distance_to_mean_b * distance_to_mean_b))

In [50]:
(fenmu_a * fenmu_b)

0.89588997178816776

In [51]:
fenzi

0.89588997178816776

In [52]:
pairwise_distances(behavior_matrix)

array([[ 0.        ,  3.36814811,  1.38869866, ...,  2.25633104,
         1.81927241,  0.49671262],
       [ 3.36814811,  0.        ,  1.98181257, ...,  1.17613565,
         1.55686152,  3.45154911],
       [ 1.38869866,  1.98181257,  0.        , ...,  0.92659449,
         0.46371962,  1.53924336],
       ..., 
       [ 2.25633104,  1.17613565,  0.92659449, ...,  0.        ,
         0.4631324 ,  2.28947416],
       [ 1.81927241,  1.55686152,  0.46371962, ...,  0.4631324 ,
         0.        ,  1.90149498],
       [ 0.49671262,  3.45154911,  1.53924336, ...,  2.28947416,
         1.90149498,  0.        ]])

In [53]:
euclidean(usr_a, usr_b)

3.3681481140879703

In [56]:
from scipy.spatial.distance import pdist, squareform

In [59]:
a = squareform(pdist(behavior_matrix))

In [60]:
behavior_matrix

0         1
uid                                
101030945        0.029148  3.974599
101306532        0.154652  0.608790
102009494        0.018775  2.585939
102027189        0.303559  0.000000
10241572         0.265665  1.964564
103402492        0.121332  1.905299
1049890          0.053085  1.672248
104991310        0.692577  0.484569
10564710         0.194293  0.515079
106531709        0.017599  2.466292
1069770          0.174749  8.898924
1079180          0.176569  0.510166
108016742        0.188523  1.747075
109954597        0.525197  0.879121
1111383          0.073820  1.317744
114225619        0.003322  1.445713
114300394        0.121772  1.616780
1145037          0.149523  1.413606
114515320        0.711838  0.448203
114520027        0.055460  1.903057
115608638        0.091148  2.200538
116739424        0.700177  0.000000
119030590        0.019035  1.714527
119591426        0.027831  1.013868
120076971        0.140121  3.846588
120845613        0.234471  2.036048
121362410        0.701131  0.850092
121806653        0.279745  2.831688
122948297        0.159476  1.377639
1230022          0.069708  0.744759
...                   ...       ...
xyiyi            0.126077  1.587895
yange1991        0.172502  0.950370
yatouzhu         0.439190  1.924215
yfqc24pippo      0.493379  2.920776
yiba             0.282241  1.024627
yicai7094        0.109643  1.310764
yinxiang         0.665925  1.225598
yizhibanjie      0.116943  3.350370
yolanta1030      0.417633  2.837445
ytrr             0.147511  2.928642
yuhanxi          0.197379  3.196016
yungweitung      0.153969  4.654077
yuuffy           0.304602  1.643040
z123456789321    0.007742  3.124715
z14759230        0.175950  0.862549
zengdi77         0.568606  0.653289
zeus93           0.106608  3.756116
zhangxiaoduo123  0.391457  0.709429
zhangyiwang      0.243508  1.720291
zhouruopei       0.524767  1.363105
zhuangdikun      0.372682  2.784053
zhushejia        0.395568  2.259548
zi1230           0.048547  2.101501
zihaozai0407     0.578905  0.603406
zmzy             0.354463  0.313900
zoe-77           0.033320  2.026757
zombieleslie     0.272161  2.023162
zurich0o0        0.425408  1.753336
zwj514235        0.212405  2.164580
zyjj141          0.521430  4.040796

[971 rows x 2 columns]

In [62]:
pd.DataFrame(a, index=behavior_matrix.index, columns=behavior_matrix.index)

uid              101030945  101306532  102009494  102027189  10241572  \
uid                                                                     
101030945         0.000000   3.368148   1.388699   3.984060  2.023903   
101306532         3.368148   0.000000   1.981813   0.626736  1.360311   
102009494         1.388699   1.981813   0.000000   2.601573  0.668627   
102027189         3.984060   0.626736   2.601573   0.000000  1.964929   
10241572          2.023903   1.360311   0.668627   1.964929  0.000000   
103402492         2.071352   1.296938   0.688323   1.913994  0.156026   
1049890           2.302475   1.068298   0.914334   1.690903  0.361439   
104991310         3.552527   0.552083   2.206755   0.621403  1.540337   
10564710          3.463460   0.101751   2.078285   0.526541  1.451241   
106531709         1.508351   1.862551   0.119653   2.482815  0.559703   
1069770           4.926478   8.290159   6.314912   8.899857  6.934957   
1079180           3.467568   0.101030   2.081762   0.525734  1.457124   
108016742         2.233218   1.138789   0.855866   1.750858  0.230765   
109954597         3.134972   0.458675   1.780363   0.906629  1.116039   
1111383           2.657230   0.713548   1.269389   1.337621  0.674670   
114225619         2.529018   0.850495   1.140331   1.476560  0.581403   
114300394         2.359638   1.008526   0.974617   1.626968  0.376376   
1145037           2.563820   0.804833   1.179601   1.421974  0.563066   
114515320         3.591870   0.579866   2.247276   0.606282  1.580639   
114520027         2.071709   1.298063   0.683867   1.919161  0.219019   
115608638         1.775144   1.593015   0.392137   2.210766  0.293497   
116739424         4.030845   0.817449   2.674208   0.396618  2.012042   
119030590         2.260094   1.114023   0.871412   1.737975  0.351205   
119591426         2.960731   0.424467   1.572097   1.050693  0.979993   
120076971         0.169416   3.237831   1.266476   3.850059  1.886207   
120845613         1.949394   1.429488   0.590682   2.037219  0.077994   
121362410         3.195951   0.597383   1.865147   0.938467  1.196527   
121806653         1.170062   2.226415   0.358466   2.831788  0.867238   
122948297         2.600228   0.768864   1.216464   1.385153  0.596453   
1230022           3.230094   0.160322   1.841884   0.780611  1.235444   
...                    ...        ...        ...        ...       ...   
xyiyi             2.388672   0.979522   1.003796   1.597783  0.401702   
yange1991         3.027625   0.342046   1.642777   0.959364  1.018464   
yatouzhu          2.090983   1.345847   0.783982   1.928989  0.178155   
yfqc24pippo       1.151543   2.336668   0.580831   2.926938  0.982952   
yiba              2.960808   0.434971   1.583385   1.024849  0.940082   
yicai7094         2.665051   0.703415   1.278409   1.325030  0.672159   
yinxiang          2.821789   0.801157   1.506430   1.278045  0.840404   
yizhibanjie       0.630373   2.741839   0.770708   3.355563  1.393763   
yolanta1030       1.201682   2.244117   0.471532   2.839737  0.886011   
ytrr              1.052633   2.319863   0.366085   2.932796  0.971291   
yuhanxi           0.796550   2.587579   0.635684   3.197780  1.233344   
yungweitung       0.690848   4.045287   2.072552   4.656480  2.691832   
yuuffy            2.347773   1.045064   0.985269   1.643041  0.323873   
z123456789321     0.850154   2.520210   0.538889   3.138686  1.188476   
z14759230         3.115510   0.254652   1.730542   0.871938  1.105660   
zengdi77          3.364835   0.416340   2.009340   0.705009  1.345813   
zeus93            0.231808   3.147693   1.173468   3.761276  1.798599   
zhangxiaoduo123   3.285210   0.257303   1.913160   0.714853  1.261423   
zhangyiwang       2.264477   1.115047   0.894344   1.721338  0.245276   
zhouruopei        2.658108   0.840224   1.323386   1.380937  0.654894   
zhuangdikun       1.239119   2.186163   0.405585   2.784911  0.826448   
zhushejia         1.753757   1.668246   0.498502   2.26142

In [63]:
usr_a = behavior_matrix.ix['zwj514235']

In [64]:
usr_b = behavior_matrix.ix['zyjj141']

In [65]:
euclidean(usr_a, usr_b)

1.9014949776171075