In [1]:
import pandas as pd
import numpy as np

In [2]:
from surprise import Dataset
from surprise import Reader

In [3]:
from UBCFBase import UBCFBase

In [4]:
reader = Reader(line_format='user item rating', sep=':')

In [5]:
data = Dataset.load_from_file('new_usr_ratings.txt', reader=reader)

In [6]:
data.split(n_folds=3)

In [7]:
trainsets = []
for trainset, testset in data.folds():
    trainsets.append(trainset)

In [8]:
first_trainset = trainsets[0]

In [9]:
first_trainset

<surprise.dataset.Trainset instance at 0x000000001625DC08>

In [10]:
first_trainset.n_users

971

In [11]:
algo = UBCFBase('new_ratings_all.txt')

In [12]:
algo.train(first_trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the behavior similarity matrix...
Done computing behavior similarity matrix


In [13]:
algo.trainset.n_users

971

In [17]:
algo.trainset_assist_rating_df

uid       iid  rating        date  comment_type
0       482  10438426       0  2014-09-29             0
1       482  10455629       0  2014-09-11             0
2       482  10463953       0  2015-07-13             0
3       482  10465145       0  2015-08-22             0
4       482  10467774       0  2016-06-05             0
5       482  10491666       5  2015-06-18             0
6       482  10533913       0  2016-10-23             0
7       482  10535568       0  2016-07-21             0
8       482  10545939       0  2014-10-08             0
9       482  10561953       0  2014-09-30             0
10      482  10574468       0  2014-09-29             0
11      482  10574622       0  2014-09-29             0
12      482  10605978       0  2014-09-29             0
13      482  10741643       0  2015-05-30             0
14      482  10757577       0  2016-03-01             0
15      482  10777687       0  2014-09-29             0
16      482  10792650       0  2015-07-02             0
17      482  10807909       0  2015-01-16             0
18      482  10831445       0  2016-05-16             0
19      482  10833919       0  2014-09-30             0
20      482  11510624       0  2014-10-08             0
21      482  11529526       0  2014-09-29             0
22      482  11589036       0  2016-01-30             0
23      482   1291543       0  2014-10-01             0
24      482   1291544       0  2014-09-29             0
25      482   1291545       0  2014-09-30             0
26      482   1291546       0  2015-05-21             0
27      482   1291548       0  2015-05-21             0
28      482   1291550       0  2014-09-11             0
29      482   1291557       0  2015-05-27             0
...     ...       ...     ...         ...           ...
587566  519   6869395       0  2013-04-13             0
587567  519   6869414       4  2013-08-17             1
587568  519   6872273       4  2013-07-06             1
587569  519   6872284       0  2012-07-01             1
587570  519   6873143       3  2017-03-18             1
587571  519   6873657       4  2014-03-23             1
587572  519   6874456       4  2013-12-01             1
587573  519   6875263       3  2015-06-23             0
587574  519   6875863       3  2015-12-25             1
587575  519   6879185       4  2014-01-31             0
587576  519   6886510       0  2011-12-05             0
587577  519   6886896       0  2012-11-23             1
587578  519   6890469       3  2012-03-17             1
587579  519   6890730       4  2012-11-11             1
587580  519   6900127       4  2011-11-06             1
587581  519   6902929       0  2012-02-26             0
587582  519   6965615       3  2013-03-31             1
587583  519   6973376       3  2013-04-30             1
587584  519   6985986       3  2011-12-16             1
587585  519   6999855       0  2012-04-28             1
587586  519   7046723       4  2014-09-16             1
587587  519   7051357       3  2013-06-05             1
587588  519   7054604       3  2014-07-12             1
587589  519   7059671       5  2014-04-20             1
587590  519   7064681       5  2013-02-24             1
587591  519   7065187       3  2014-11-02             1
587592  519   7065238       0  2016-10-29             1
587593  519  23712691       5  1800-01-01             2
587594  519  25779218       5  1800-01-01             2
587595  519   7564975       0  2014-11-28             1

[587596 rows x 5 columns]

In [19]:
len(algo.UCI)

971

In [21]:
len(algo.URDI)

971

In [23]:
algo.behavior_sim

uid       0         1         2         3         4         5         6    \
uid                                                                         
0    0.000000  0.581619  0.872990  2.281616  1.110506  1.279491  1.011782   
1    0.581619  0.000000  1.408363  2.862514  0.531453  1.810946  1.579409   
2    0.872990  1.408363  0.000000  1.548980  1.933910  0.406754  0.265036   
3    2.281616  2.862514  1.548980  0.000000  3.392090  1.256166  1.312824   
4    1.110506  0.531453  1.933910  3.392090  0.000000  2.333230  2.110556   
5    1.279491  1.810946  0.406754  1.256166  2.333230  0.000000  0.371814   
6    1.011782  1.579409  0.265036  1.312824  2.110556  0.371814  0.000000   
7    0.785795  0.207697  1.615220  3.067410  0.324810  2.017003  1.786962   
8    0.575657  1.154129  0.394960  1.709194  1.684869  0.766397  0.446915   
9    1.993097  1.418688  2.739828  4.255815  0.930156  3.116711  2.949193   
10   0.882910  0.401339  1.585466  3.106595  0.485924  1.965953  1.796677   
11   1.045155  0.510268  1.771374  3.287805  0.369706  2.153119  1.979666   
12   1.795248  1.228984  2.523860  4.046601  0.773006  2.897490  2.737355   
13   0.623498  1.133475  0.281577  1.818953  1.655916  0.677686  0.509300   
14   1.279628  0.763779  1.956263  3.490227  0.531936  2.323915  2.177811   
15   0.952200  0.480588  1.631577  3.160153  0.512957  2.006461  1.848474   
16   2.426531  3.007214  1.685580  0.145951  3.537035  1.380648  1.453214   
17   1.864390  1.296199  2.595685  4.117774  0.831178  2.969437  2.808807   
18   0.128127  0.708512  0.754583  2.154134  1.238183  1.159935  0.884747   
19   1.403494  0.821965  2.201442  3.683023  0.308906  2.594270  2.390762   
20   2.130825  1.550609  2.902305  4.405151  1.038023  3.285025  3.104282   
21   1.199855  0.634520  1.954669  3.461245  0.286207  2.340038  2.157099   
22   3.374955  3.955658  2.619331  1.093426  4.485453  2.284973  2.396142   
23   0.463358  0.668559  0.850622  2.391672  1.145163  1.223079  1.079698   
24   2.403592  1.822102  3.197831  4.684385  1.295328  3.585689  3.391863   
25   1.344708  0.763755  2.137507  3.622755  0.264704  2.529579  2.328518   
26   0.057965  0.580458  0.849572  2.283169  1.111729  1.256276  1.001554   
27   0.353025  0.828130  0.583279  2.093309  1.351017  0.983084  0.782292   
28   0.417731  0.230352  1.191644  2.673284  0.742504  1.590875  1.375958   
29   0.952532  0.375646  1.745154  3.227967  0.217012  2.140026  1.933407   
..        ...       ...       ...       ...       ...       ...       ...   
941  2.382722  1.806024  3.130813  4.647698  1.304721  3.505844  3.341084   
942  2.998548  2.417269  3.771556  5.275314  1.896087  4.151522  3.974969   
943  1.717145  1.135624  2.509074  3.996308  0.616583  2.898940  2.702118   
944  1.281532  0.703114  2.104770  3.562952  0.171699  2.503373  2.282252   
945  2.593182  2.027679  3.298054  4.832590  1.552963  3.659244  3.520491   
946  2.021673  1.472598  2.702836  4.241237  1.049837  3.061700  2.928487   
947  2.654743  2.090218  3.355474  4.891407  1.616889  3.715032  3.579060   
948  2.306711  1.729266  3.059527  4.573743  1.226206  3.436276  3.268135   
949  2.248937  1.667914  3.050802  4.530393  1.139171  3.441181  3.241223   
950  2.008611  1.427522  2.811881  4.290017  0.899146  3.203377  3.001116   
951  1.658882  1.077700  2.464997  3.940209  0.550276  2.858455  2.651940   
952  2.988632  2.408450  3.792785  5.270214  1.878130  4.182033  3.983386   
953  1.512288  0.931776  2.325014  3.793879  0.402352  2.720542  2.508454   
954  1.748645  1.169833  2.519007  4.021095  0.669414  2.903469  2.719974   
955  3.000474  2.419380  3.770758  5.276367  1.899308  4.149896  3.975152   
956  2.516954  1.940936  3.259859  4.779699  1.440596  3.632729  3.472042   
957  2.239695  1.682429  2.931566  4.468381  1.233108  3.291465  3.155827   
958  2.094289  1.514528  2.905732  4.375823  0.983794  3.299042  3.091394   
959  2.576347  1.996301  3.383332  4.857914  1.465841  3.774251  3.572013

In [26]:
np.shape(algo.sim)

(971L, 971L)

In [29]:
user_behavior_matrix = pd.concat([algo.UCI, algo.URDI], axis=1)

In [30]:
from sklearn.metrics.pairwise import pairwise_distances


In [31]:
user_behavior_matrix

0         1
uid                    
0    0.034986  2.988429
1    0.064893  2.407580
2    0.426395  3.768756
3    0.044903  5.270024
4    0.020021  1.878025
5    0.593091  4.139784
6    0.259831  3.974912
7    0.031137  2.202644
8    0.090227  3.561430
9    0.400074  1.029055
10   0.397882  2.183546
11   0.369619  1.998293
12   0.463913  1.245175
13   0.408378  3.487757
14   0.548364  1.816299
15   0.462466  2.137579
16   0.063433  5.414793
17   0.460723  1.173299
18   0.048027  3.115891
19   0.126077  1.587895
20   0.270386  0.870648
21   0.299903  1.818185
22   0.066448  6.363238
23   0.493379  2.920776
24   0.114649  0.586158
25   0.152517  1.648868
26   0.092941  2.987360
27   0.321239  3.195034
28   0.190450  2.600705
29   0.159713  2.044098
..        ...       ...
941  0.425601  0.637943
942  0.281112  0.000000
943  0.148939  1.275070
944  0.001414  1.707337
945  0.700565  0.482118
946  0.702193  1.080028
947  0.734246  0.427434
948  0.391457  0.709429
949  0.063058  0.739667
950  0.066063  0.980058
951  0.068462  1.329885
952  0.000141  0.000000
953  0.039565  1.476148
954  0.264730  1.254942
955  0.303559  0.000000
956  0.468985  0.509175
957  0.701131  0.850092
958  0.000353  0.894427
959  0.000707  0.412311
960  0.700353  0.297647
961  0.381626  0.692308
962  0.269123  0.349927
963  0.700106  0.333333
964  0.000035  0.000000
965  0.700177  0.565685
966  0.700177  0.000000
967  0.700035  0.000000
968  0.700106  0.000000
969  0.000035  0.000000
970  0.700035  0.000000

[971 rows x 2 columns]

In [32]:
pairwise_distances(user_behavior_matrix, metric='euclidean')

array([[  0.00000000e+00,   5.81619077e-01,   8.72989810e-01, ...,
          3.06155099e+00,   2.98863372e+00,   3.06153563e+00],
       [  5.81619077e-01,   0.00000000e+00,   1.40836290e+00, ...,
          2.48996707e+00,   2.40845309e+00,   2.48994904e+00],
       [  8.72989810e-01,   1.40836290e+00,   0.00000000e+00, ...,
          3.77868256e+00,   3.79279671e+00,   3.77867744e+00],
       ..., 
       [  3.06155099e+00,   2.48996707e+00,   3.77868256e+00, ...,
          0.00000000e+00,   7.00070680e-01,   7.06797034e-05],
       [  2.98863372e+00,   2.40845309e+00,   3.79279671e+00, ...,
          7.00070680e-01,   0.00000000e+00,   7.00000000e-01],
       [  3.06153563e+00,   2.48994904e+00,   3.77867744e+00, ...,
          7.06797034e-05,   7.00000000e-01,   0.00000000e+00]])

In [33]:
algo.behavior_sim

uid       0         1         2         3         4         5         6    \
uid                                                                         
0    0.000000  0.581619  0.872990  2.281616  1.110506  1.279491  1.011782   
1    0.581619  0.000000  1.408363  2.862514  0.531453  1.810946  1.579409   
2    0.872990  1.408363  0.000000  1.548980  1.933910  0.406754  0.265036   
3    2.281616  2.862514  1.548980  0.000000  3.392090  1.256166  1.312824   
4    1.110506  0.531453  1.933910  3.392090  0.000000  2.333230  2.110556   
5    1.279491  1.810946  0.406754  1.256166  2.333230  0.000000  0.371814   
6    1.011782  1.579409  0.265036  1.312824  2.110556  0.371814  0.000000   
7    0.785795  0.207697  1.615220  3.067410  0.324810  2.017003  1.786962   
8    0.575657  1.154129  0.394960  1.709194  1.684869  0.766397  0.446915   
9    1.993097  1.418688  2.739828  4.255815  0.930156  3.116711  2.949193   
10   0.882910  0.401339  1.585466  3.106595  0.485924  1.965953  1.796677   
11   1.045155  0.510268  1.771374  3.287805  0.369706  2.153119  1.979666   
12   1.795248  1.228984  2.523860  4.046601  0.773006  2.897490  2.737355   
13   0.623498  1.133475  0.281577  1.818953  1.655916  0.677686  0.509300   
14   1.279628  0.763779  1.956263  3.490227  0.531936  2.323915  2.177811   
15   0.952200  0.480588  1.631577  3.160153  0.512957  2.006461  1.848474   
16   2.426531  3.007214  1.685580  0.145951  3.537035  1.380648  1.453214   
17   1.864390  1.296199  2.595685  4.117774  0.831178  2.969437  2.808807   
18   0.128127  0.708512  0.754583  2.154134  1.238183  1.159935  0.884747   
19   1.403494  0.821965  2.201442  3.683023  0.308906  2.594270  2.390762   
20   2.130825  1.550609  2.902305  4.405151  1.038023  3.285025  3.104282   
21   1.199855  0.634520  1.954669  3.461245  0.286207  2.340038  2.157099   
22   3.374955  3.955658  2.619331  1.093426  4.485453  2.284973  2.396142   
23   0.463358  0.668559  0.850622  2.391672  1.145163  1.223079  1.079698   
24   2.403592  1.822102  3.197831  4.684385  1.295328  3.585689  3.391863   
25   1.344708  0.763755  2.137507  3.622755  0.264704  2.529579  2.328518   
26   0.057965  0.580458  0.849572  2.283169  1.111729  1.256276  1.001554   
27   0.353025  0.828130  0.583279  2.093309  1.351017  0.983084  0.782292   
28   0.417731  0.230352  1.191644  2.673284  0.742504  1.590875  1.375958   
29   0.952532  0.375646  1.745154  3.227967  0.217012  2.140026  1.933407   
..        ...       ...       ...       ...       ...       ...       ...   
941  2.382722  1.806024  3.130813  4.647698  1.304721  3.505844  3.341084   
942  2.998548  2.417269  3.771556  5.275314  1.896087  4.151522  3.974969   
943  1.717145  1.135624  2.509074  3.996308  0.616583  2.898940  2.702118   
944  1.281532  0.703114  2.104770  3.562952  0.171699  2.503373  2.282252   
945  2.593182  2.027679  3.298054  4.832590  1.552963  3.659244  3.520491   
946  2.021673  1.472598  2.702836  4.241237  1.049837  3.061700  2.928487   
947  2.654743  2.090218  3.355474  4.891407  1.616889  3.715032  3.579060   
948  2.306711  1.729266  3.059527  4.573743  1.226206  3.436276  3.268135   
949  2.248937  1.667914  3.050802  4.530393  1.139171  3.441181  3.241223   
950  2.008611  1.427522  2.811881  4.290017  0.899146  3.203377  3.001116   
951  1.658882  1.077700  2.464997  3.940209  0.550276  2.858455  2.651940   
952  2.988632  2.408450  3.792785  5.270214  1.878130  4.182033  3.983386   
953  1.512288  0.931776  2.325014  3.793879  0.402352  2.720542  2.508454   
954  1.748645  1.169833  2.519007  4.021095  0.669414  2.903469  2.719974   
955  3.000474  2.419380  3.770758  5.276367  1.899308  4.149896  3.975152   
956  2.516954  1.940936  3.259859  4.779699  1.440596  3.632729  3.472042   
957  2.239695  1.682429  2.931566  4.468381  1.233108  3.291465  3.155827   
958  2.094289  1.514528  2.905732  4.375823  0.983794  3.299042  3.091394   
959  2.576347  1.996301  3.383332  4.857914  1.465841  3.774251  3.572013

In [39]:
a_items = [item for item, rating in algo.trainset.ur[0]]

In [40]:
b_items = [item for item, rating in algo.trainset.ur[1]]

In [43]:
len(np.intersect1d(a_items, b_items, assume_unique=True))

45

In [44]:
count = 0
for i in a_items:
    if i in b_items:
        count += 1

In [45]:
count

44

In [48]:
np.array((3, 5), 4)

TypeError: data type not understood

In [51]:
np.empty((2, 2), dtype=bool)

array([[False, False],
       [False, False]], dtype=bool)

In [52]:
n_users = algo.trainset.n_users

In [53]:
n_users

971

In [62]:
placeholder = np.empty((n_users, n_users), dtype=bool)

In [63]:
placeholder

array([[ True,  True,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [ True,  True,  True, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False,  True]], dtype=bool)

In [64]:
range(971)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [65]:
for i in range(971):
    for j in range(971):
        placeholder[i, j] = False

In [66]:
placeholder

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [68]:
    def count_user_share_ratings( u, v):

        u_rating_item = [item for item, rating in algo.trainset.ur[u]]
        v_rating_item = [item for item, rating in algo.trainset.ur[v]]

        return len(np.intersect1d(u_rating_item, v_rating_item))

In [69]:
for i in range(971):
    for j in range(971):
        placeholder[i, j] = count_user_share_ratings(i, j)

In [70]:
placeholder

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ...,  True, False, False],
       ..., 
       [False, False,  True, ...,  True, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False,  True]], dtype=bool)

In [74]:
n_users = algo.trainset.n_users
placeholder = np.empty((n_users, n_users), dtype=int)

user_rating_items = {}

for u in range(n_users):
    user_rating_items[u] = [item for item, rating in algo.trainset.ur[u]]

In [80]:
count = 0
for i in range(n_users):
    for j in range(n_users):
        placeholder[i, j] = len(np.intersect1d(user_rating_items[i], user_rating_items[j], assume_unique=True))

In [81]:
placeholder

array([[283,  45,  50, ...,   0,   0,   0],
       [ 45, 732, 137, ...,   1,   1,   1],
       [ 50, 137, 693, ...,   3,   2,   2],
       ..., 
       [  0,   1,   3, ...,   3,   0,   0],
       [  0,   1,   2, ...,   0,   1,   0],
       [  0,   1,   2, ...,   0,   0,   1]])

In [78]:
algo.assist_rating_df

uid       iid  rating        date  comment_type
0       101030945  10438426       0  2014-09-29             0
1       101030945  10455629       0  2014-09-11             0
2       101030945  10463953       0  2015-07-13             0
3       101030945  10465145       0  2015-08-22             0
4       101030945  10467774       0  2016-06-05             0
5       101030945  10491666       5  2015-06-18             0
6       101030945  10533913       0  2016-10-23             0
7       101030945  10535568       0  2016-07-21             0
8       101030945  10545939       0  2014-10-08             0
9       101030945  10561953       0  2014-09-30             0
10      101030945  10574468       0  2014-09-29             0
11      101030945  10574622       0  2014-09-29             0
12      101030945  10605978       0  2014-09-29             0
13      101030945  10741643       0  2015-05-30             0
14      101030945  10757577       0  2016-03-01             0
15      101030945  10777687       0  2014-09-29             0
16      101030945  10792650       0  2015-07-02             0
17      101030945  10807909       0  2015-01-16             0
18      101030945  10831445       0  2016-05-16             0
19      101030945  10833919       0  2014-09-30             0
20      101030945  11510624       0  2014-10-08             0
21      101030945  11529526       0  2014-09-29             0
22      101030945  11589036       0  2016-01-30             0
23      101030945   1291543       0  2014-10-01             0
24      101030945   1291544       0  2014-09-29             0
25      101030945   1291545       0  2014-09-30             0
26      101030945   1291546       0  2015-05-21             0
27      101030945   1291548       0  2015-05-21             0
28      101030945   1291550       0  2014-09-11             0
29      101030945   1291557       0  2015-05-27             0
...           ...       ...     ...         ...           ...
587566    zyjj141   6869395       0  2013-04-13             0
587567    zyjj141   6869414       4  2013-08-17             1
587568    zyjj141   6872273       4  2013-07-06             1
587569    zyjj141   6872284       0  2012-07-01             1
587570    zyjj141   6873143       3  2017-03-18             1
587571    zyjj141   6873657       4  2014-03-23             1
587572    zyjj141   6874456       4  2013-12-01             1
587573    zyjj141   6875263       3  2015-06-23             0
587574    zyjj141   6875863       3  2015-12-25             1
587575    zyjj141   6879185       4  2014-01-31             0
587576    zyjj141   6886510       0  2011-12-05             0
587577    zyjj141   6886896       0  2012-11-23             1
587578    zyjj141   6890469       3  2012-03-17             1
587579    zyjj141   6890730       4  2012-11-11             1
587580    zyjj141   6900127       4  2011-11-06             1
587581    zyjj141   6902929       0  2012-02-26             0
587582    zyjj141   6965615       3  2013-03-31             1
587583    zyjj141   6973376       3  2013-04-30             1
587584    zyjj141   6985986       3  2011-12-16             1
587585    zyjj141   6999855       0  2012-04-28             1
587586    zyjj141   7046723       4  2014-09-16             1
587587    zyjj141   7051357       3  2013-06-05             1
587588    zyjj141   7054604       3  2014-07-12             1
587589    zyjj141   7059671       5  2014-04-20             1
587590    zyjj141   7064681       5  2013-02-24             1
587591    zyjj141   7065187       3  2014-11-02             1
587592    zyjj141   7065238       0  2016-10-29             1
587593    zyjj141  23712691       5  1800-01-01             2
587594    zyjj141  25779218       5  1800-01-01             2
587595    zyjj141   7564975       0  2014-11-28             1

[587596 rows x 5 columns]

In [79]:
algo.trainset.n_items

38494

In [82]:
algo.trainset.offset

0